version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testpass!
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    volumes:
      - pg-data:/var/lib/postgresql/data
      
volumes:
  pg-data:
    driver: local
