version: '3.9'

services:

  db:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testrootpass!
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass
    ports:
      - 3306:3306
    volumes:
      - ~/mysql:/var/lib/mysql
